### PR TITLE
Add support for unpublished exceptions on the verify-image API endpoint

### PR DESCRIPTION
**Pull request by mprahl**
The first two commits fix the unit tests.

### CODE REVIEW

**Comment by mprahl** [comment]
It seems there is an additional test failure due to SQLAlchemy 1.4 being used for the tests.

**Review by apaplaus — APPROVED** [review]

**Comment by apaplaus** [comment]
As I see there are still some pipeline fails.

**Comment by apaplaus** [comment]
So should something be done with those fails?

**Review by apaplaus — APPROVED** [review]

**Comment by mprahl** [comment]
@apaplaus for some reason, TravisCI is not running on my last two pushes.

**Comment by mprahl** [comment]
@apaplaus it seems that we ran out of TravisCI tokens so I am trying to migrate us to use GitHub actions

**Comment by mprahl** [comment]
@apaplaus, I moved the commits that fixed the unit tests to #70

**Pull request merged**
